### ISSUE TITLE
gpg_import fails with "import failed"

### ISSUE THREAD

**Issue by enko** [php-gnupg/php-gnupg#11]
When I try to import a 4096-Bit RSA key I have created with gpg 1.4.18, it just fails me with „import failed“.

You can get a example project with demo keys using docker-compose here:

https://code.flyacts.com/tsc/gnupg-import-error

Run these commands to reproduce the issue:

```
$ docker-compose build
$ docker-compose up -d
$ docker-compose exec web bash
# php test.php
# exit
$ docker-compose down
```

The output I get is this:

```
root@f996527350a1:/var/www/html# php test.php
array(2) {
  [0]=>
  bool(false)
  [1]=>
  string(13) "import failed"
}
array(2) {
  [0]=>
  bool(false)
  [1]=>
  string(13) "import failed"
}
```

I would expect that the import works or at least give me a reasonable error message so I can figure out whats wrong.

**Comment by cagiant** [comment]
I have the same issue. who can help?

**Comment by travispaul** [comment]
I was struggling with this myself today.  I received the "import failed" error when running under fpm but unit tests and the development server (`php -S`) were both successful.

In my case, the issue was that the `PATH` and `HOME` environment variables were not set by fpm. php-gnupg (or more likely gpgme) will also end up creating a .gnupg directory so the user running your webserver also needs write access to the directory you set for `HOME`. A quick grep of the gpgme source suggests that `PATH` is necessary for  gpgme to  `execv` some utilities.

Hope that helps someone!

**Comment by AEQPAC** [comment]
Hello, same issue here.
I'm using PHP Apache with brew on a mac, son basically, httpd server runs with my own user.
Where should I check those ENV variable ? Directly on the system or on Apache / PHP conf ?

**Comment by travispaul** [comment]
@AEQPAC In your case probably apache, a quick way to diagnose would just be to use `getenv()` in a script ran by the webserver to see if they're set. Apache has a `SetEnv`  directive you can use (or at least the last version of Apache I used)

**Comment by AEQPAC** [comment]
@travispaul With Apache, my `HOME` is fine but my `PATH` lacks a lot of directories.
I'll investigate on this, thank you.

**Comment by AEQPAC** [comment]
@travispaul I updated the variable, now it's the same as php cli but... still "import failed" :(

**Comment by travispaul** [comment]
@AEQPAC The only other thing I recall running into are file permissions when the webserver user and the owner of the keys/home directory differ. 

But you did state:

> httpd server runs with my own user.

So that may not be the case here.

When using php-gnupg on the command line or with the builtin php webserver (`php -S`) does the import succeed?

**Comment by AEQPAC** [comment]
> When using php-gnupg on the command line or with the builtin php webserver (php -S) does the import succeed?
Yes

**Comment by AEQPAC** [comment]
@travispaul It's ok, thanks a lot for your time.
So yeah, I'll just stash this part for now, but I'm still open to suggestions.

**Comment by bukka** [comment]
Note that there's an option in version 1.5 to set home directly as a constructor parameter: https://github.com/php-gnupg/php-gnupg/blob/gnupg-1.5.0/tests/gnupg_oo_init_home_dir.phpt#L13 . The docs still needs to be updated so will leave this open as a reminder to update it.

**Comment by bukka** [comment]
Docs have been updated: https://www.php.net/manual/en/function.gnupg-init.php

Closing this. If you still see an issue with version 1.5, please open a new issue.
