### ISSUE TITLE
Pass By Reference Issue

### ISSUE THREAD

**Issue by travisghansen** [php-gnupg/php-gnupg#4]
I'm trying to run my unit tests for https://github.com/travisghansen/phpgpg in a php7 environment with 1.4.0-rc1 installed.

Apparently now PHP 7 handles this is differently now?

```Parameter 2 to gnupg::decryptverify() expected to be a reference, value given```

Invoking as such:
```
$plaintext = null;
$info = $this->getResource()->decryptverify($data, $plaintext);
```

Thanks!

**Comment by bukka** [comment]
I just tried to run your tests on the PHP 7 (master and latest PHP-7.0 which is 7.0.9-dev) and it worked fine for the first time. It just failed later due to not cleaning keychain:

```
1) PhpGpg\Tests\Unit\KeyTest::testImportPublicKey
Failed asserting that 5 matches expected 4.

/home/jakub/prog/gnupg/phpgpg/tests/Unit/KeyTest.php:20
```

After I cleaned it manually then it worked again.

However it doesn't seem to be related to your report. Are able to give me a minimal script without using your library (directly using gnupg) to recreate it.

**Comment by travisghansen** [comment]
@bukka by default it uses the cli adapter.  Hack ```tests/config.php``` to activate ```PhpGpg\PhpGpg::setDefaultDriver('\PhpGpg\Driver\GnuPG\GpgMe');```

**Comment by bukka** [comment]
Ok thanks. I'm able to recreate it. Will take a look later

**Comment by travisghansen** [comment]
@bukka awesome thanks!

**Comment by travisghansen** [comment]
You may want to use the ```./run_tests.sh``` as that is what cleans the keychains before executing the tests.

**Comment by bukka** [comment]
So I have investigated it and the version 5 used quite non-standard way how to deal with passing by ref. It basically took the original value (zval) without specifying that it will be used as ref. This worked fine on PHP 5 but PHP 7 needs to declare these things in the standard way (using arginfo) otherwise it won't  modify the value.

However using the reference in that way is not allowed for call_user_func_array. This is common for the user space functions as you can see in https://3v4l.org/ctZWI .

I'm afraid I can't do anything. I should probably add some updgrading note so I will keep it open till I add it. But the only solution that I see atm. is that you update your code because it worked just because of the ext hack that is not in line with how the user space functions work...

**Comment by travisghansen** [comment]
@bukka I don't think the issue *is* in my code.  It's the extension that has it declared as pass by ref.  I've seen a few other similar bugs for PHP 7 so I'll dig those up and see if they help.

**Comment by travisghansen** [comment]
Actually I see what you're referring to regarding the user func.  I'll see if I can work around it and report back here my findings.

**Comment by travisghansen** [comment]
@bukka so I got this to work with both PHP5 and PHP7 using the following: https://github.com/travisghansen/phpgpg/commit/bab981a239b2148df23e8282e3b45388aa51afae

Thanks for taking the time to review and help me come to a solution!

**Comment by bukka** [comment]
Nice! I have added an [UPGRADING file](https://github.com/php-gnupg/php-gnupg/blob/1035e8a557035fae2b7aff51ace7812ffbbdcbce/UPGRADING) with info about this change. So closing.
